version: "3"

services:
    redis:
        image: redis:5
    app:
        build: .
        command: ["npm", "run", "devstart"]
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
        depends_on:
            - redis
        environment:
            - NODE_ENV=development
            - PORT=3000
            # - REDIS_URL=redis://cache
            - REDIS_HOST=redis
